"""Appliance configuration.

Configuration is a single YAML file (FR-04). Default location is
/etc/tl-commissioning-source/config.yaml, overridable with the
TL_SOURCE_CONFIG environment variable so development and tests can run
from a scratch directory. Secrets (the control PIN) are stored as a salted
hash and are excluded from config export (FR-05, FR-30).
"""

from __future__ import annotations

import copy
import hashlib
import json
import os
import secrets
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

DEFAULT_CONFIG_PATH = "/etc/tl-commissioning-source/config.yaml"

DEFAULTS: dict[str, Any] = {
    "appliance": {
        "id": "",  # generated on first init, e.g. TL-TESTSOURCE-01
        "friendly_name": "Transition Layer Test Source",
        "source_number": 1,
    },
    "branding": {
        "company_name": "Transition Layer",
        "logo_path": "",  # empty -> built-in placeholder mark
        "accent_colour": "#00d4aa",
        "report_footer": "Commissioning record generated by the Transition Layer test source.",
    },
    "engineer": {
        "default_name": "",
    },
    "server": {
        "bind_host": "0.0.0.0",
        "port": 8808,
        "external_url": "",  # optional override for QR code, e.g. http://tl-source.local:8808
    },
    "security": {
        "pin_hash": "",  # salted sha256, set via first-run or CLI; empty -> setup not complete
        "pin_salt": "",
        "token_ttl_seconds": 43200,
        "setup_complete": False,
        # Set false to disable PIN/token protection entirely (open LAN
        # control). Default true - the brief's AC-13 requires protection,
        # so the shipped default keeps it on; operators may opt out.
        "require_pin": True,
        # Optional static bearer token for integrations (OpenAVC, Ansible
        # validation). Empty = disabled. Set via `tl-source init --api-token`
        # or --generate-api-token; never exported (FR-05).
        "api_token": "",
    },
    "output": {
        "preferred_connector": "",  # empty -> first connected output
        "default_mode": "",  # e.g. "1920x1080@60"; empty -> current mode
        # Pattern shown when the backend starts: the Identify screen makes
        # the appliance self-describing from power-on (source number,
        # control URL, panel QR). Set "holding" for a black screen until
        # a pattern is explicitly activated (FR-07 strict behaviour).
        "startup_pattern": "identify",
    },
    "audio": {
        "preferred_sink": "",  # empty -> first HDMI sink
    },
    "soak": {
        "default_minutes": 30,
        "audio_enabled": True,
    },
    "storage": {
        "data_dir": "/var/lib/tl-commissioning-source",
        "reports_dir": "/var/lib/tl-commissioning-source/reports",
        "evidence_dir": "/var/lib/tl-commissioning-source/evidence",
        "low_disk_warn_mb": 1024,
        "max_photo_mb": 25,
        "report_retention_days": 0,  # 0 = keep forever
    },
    "report": {
        "chromium_path": "",  # empty -> autodetect
    },
    "hardware": {
        "display_backend": "auto",  # auto | xrandr | mock
        "audio_backend": "auto",  # auto | pactl | mock
    },
    "integration": {
        # URL of a room-control panel (e.g. an OpenAVC panel:
        # http://<host>:8080/panel). When set, the Identify screen shows a
        # "scan for room control" QR pointing at it.
        "panel_url": "",
    },
}

_SECRET_KEYS = {
    ("security", "pin_hash"),
    ("security", "pin_salt"),
    ("security", "api_token"),
}


def _deep_merge(base: dict, override: dict) -> dict:
    out = copy.deepcopy(base)
    for key, value in override.items():
        if key in out and isinstance(out[key], dict) and isinstance(value, dict):
            out[key] = _deep_merge(out[key], value)
        else:
            out[key] = copy.deepcopy(value)
    return out


@dataclass
class Config:
    path: Path
    data: dict[str, Any] = field(default_factory=lambda: copy.deepcopy(DEFAULTS))

    # -- access ---------------------------------------------------------
    def get(self, *keys: str, default: Any = None) -> Any:
        node: Any = self.data
        for key in keys:
            if not isinstance(node, dict) or key not in node:
                return default
            node = node[key]
        return node

    def set(self, keys: tuple[str, ...], value: Any) -> None:
        node = self.data
        for key in keys[:-1]:
            node = node.setdefault(key, {})
        node[keys[-1]] = value

    # -- storage paths ----------------------------------------------------
    @property
    def data_dir(self) -> Path:
        return Path(self.get("storage", "data_dir"))

    @property
    def db_path(self) -> Path:
        return self.data_dir / "app.db"

    @property
    def reports_dir(self) -> Path:
        return Path(self.get("storage", "reports_dir"))

    @property
    def evidence_dir(self) -> Path:
        return Path(self.get("storage", "evidence_dir"))

    def ensure_dirs(self) -> None:
        for path in (self.data_dir, self.reports_dir, self.evidence_dir):
            path.mkdir(parents=True, exist_ok=True)

    # -- PIN ------------------------------------------------------------
    def set_pin(self, pin: str) -> None:
        if not pin or len(pin) < 4:
            raise ValueError("PIN must be at least 4 characters")
        salt = secrets.token_hex(16)
        self.set(("security", "pin_salt"), salt)
        self.set(("security", "pin_hash"), _hash_pin(pin, salt))

    def check_pin(self, pin: str) -> bool:
        salt = self.get("security", "pin_salt") or ""
        stored = self.get("security", "pin_hash") or ""
        if not stored:
            return False
        return secrets.compare_digest(_hash_pin(pin, salt), stored)

    @property
    def setup_complete(self) -> bool:
        return bool(self.get("security", "setup_complete"))

    # -- persistence ------------------------------------------------------
    def save(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        tmp = self.path.with_suffix(".tmp")
        with open(tmp, "w", encoding="utf-8") as fh:
            yaml.safe_dump(self.data, fh, sort_keys=False)
        os.replace(tmp, self.path)

    def export_public(self) -> dict[str, Any]:
        """Non-secret configuration as a JSON-safe dict (FR-05)."""
        out = copy.deepcopy(self.data)
        for section, key in _SECRET_KEYS:
            out.get(section, {}).pop(key, None)
        return out

    def import_public(self, incoming: dict[str, Any]) -> None:
        """Merge an exported configuration, refusing secret keys."""
        cleaned = copy.deepcopy(incoming)
        for section, key in _SECRET_KEYS:
            cleaned.get(section, {}).pop(key, None)
        self.data = _deep_merge(self.data, cleaned)


def _hash_pin(pin: str, salt: str) -> str:
    return hashlib.sha256(f"{salt}:{pin}".encode()).hexdigest()


def config_path() -> Path:
    return Path(os.environ.get("TL_SOURCE_CONFIG", DEFAULT_CONFIG_PATH))


def load_config(path: Path | None = None) -> Config:
    path = path or config_path()
    data = copy.deepcopy(DEFAULTS)
    if path.exists():
        with open(path, encoding="utf-8") as fh:
            loaded = yaml.safe_load(fh) or {}
        if not isinstance(loaded, dict):
            raise ValueError(f"Configuration file {path} is not a mapping")
        data = _deep_merge(data, loaded)
    return Config(path=path, data=data)


def schema() -> dict[str, Any]:
    """Published configuration schema (§12)."""
    schema_file = Path(__file__).parent / "config.schema.json"
    return json.loads(schema_file.read_text(encoding="utf-8"))
